### ISSUE TITLE
Commercial use?

### ISSUE THREAD

**Issue by RyanBram** [wothke/webaudio-player#1]
Is there any commercial license for using your libraries, including the add on (webxmp, webmpt)?

**Comment by wothke** [comment]
In principle I am happy to provide commercial licenses for my work (e.g. this player). If you are interested drop me a PM and we can work out something reasonable: info[A]wothke.ch

However the situation for add-ons is somewhat more complicated since many of those original projects (that my code is based on) use some GPL type license that I cannot change for my versions unless the original projects already provide some type of double licensing scheme. If the respective original projects  (e.g. openMPT) already do provide some type of alternative commercial license (which so far I haven't checked) then I'd be happy to also provide respective licensing for my web additions.

**Comment by RyanBram** [comment]
Thank you very much for your information.
